spring:
  application:
    name: spring-ai-chatbots
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:your-api-key}

server:
  port: 8081

logging:
  level:
    root: debug

springdoc:
  swagger-ui:
    url: /swagger-ui.html